### PR TITLE
🐛 Fix incorrect npm install command [nom-60]

### PR DESCRIPTION
**Pull request by bothzoli**
The install command for npm in `README.md` was incorrect.

## Checklist

-   [x] The commit message are organized for human readability
-   [x] The branch has is appended with the issue, e.g., `branch-name-nom-32`
-   [x] Commit messages are appended with the issue number, e.g., `✨ short commit message [nom-32]`
-   [x] Commit messages follow our [convention](../README.md#Commit-Log-Standards).
-   [x] Docs have been added / updated (for bug fixes / features)
-   [ ] Tests for the changes have been added (for bug fixes / features)

## What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)

-   [ ] ✨ new feature
-   [x] 🐛 bug fix
-   [ ] 💅 style
-   [ ] 🧼 chore
-   [ ] 📝 docs
-   [ ] 🐎 performance
-   [ ] 🧪 tests
-   [ ] 🏗️ refactor
-   [ ] 🧰 tooling / infrastructure

## Which issue does this address?

https://github.com/stephencweiss/note-mgr/issues/60

## Breaking Change?

-   Does this PR introduce a breaking change? No
-   What changes might users need to make in their application due to this PR? None

### CODE REVIEW

**Comment by stephencweiss** [comment]
@bothzoli thanks! While you're at it, want to update the `yarn` command two lines above?

**Comment by bothzoli** [comment]
sure thing, i'll look into it 😊

**Comment by bothzoli** [comment]
> @bothzoli thanks! While you're at it, want to update the `yarn` command two lines above?

done 😊

**Review by stephencweiss — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
